apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miapp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: encuestapp.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: miapp-service
            port:
              number: 8080
